//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuvTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DynamicValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DynamicValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuvTools.Resources.DynamicValidationMessages", typeof(DynamicValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of these parameters should be filled: {0}..
        /// </summary>
        public static string AtLeastOneTheseParametersShoudBeFilledX {
            get {
                return ResourceManager.GetString("AtLeastOneTheseParametersShoudBeFilledX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date {0} must be after date {1}..
        /// </summary>
        public static string DateXMustBeAfterDateY {
            get {
                return ResourceManager.GetString("DateXMustBeAfterDateY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail {0} is already taken..
        /// </summary>
        public static string EmailXAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailXAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        public static string XInvalid {
            get {
                return ResourceManager.GetString("XInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be equal {1}..
        /// </summary>
        public static string XMustBeEqualY {
            get {
                return ResourceManager.GetString("XMustBeEqualY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least {1} capital letter(s)..
        /// </summary>
        public static string XMustContainAtLeastYCapitalLetters {
            get {
                return ResourceManager.GetString("XMustContainAtLeastYCapitalLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least {1} digit(s)..
        /// </summary>
        public static string XMustContainAtLeastYDigits {
            get {
                return ResourceManager.GetString("XMustContainAtLeastYDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least {1} lower case letter(s)..
        /// </summary>
        public static string XMustContainAtLeastYLowerCaseLetters {
            get {
                return ResourceManager.GetString("XMustContainAtLeastYLowerCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain between {1} and {2} character(s)..
        /// </summary>
        public static string XMustContainBetweenYandZCharacters {
            get {
                return ResourceManager.GetString("XMustContainBetweenYandZCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must have at least {1} character(s)..
        /// </summary>
        public static string XMustHaveAtLeastYCharacters {
            get {
                return ResourceManager.GetString("XMustHaveAtLeastYCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must have up to {1} character(s)..
        /// </summary>
        public static string XMustHaveUpToYCharacters {
            get {
                return ResourceManager.GetString("XMustHaveUpToYCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string XRequired {
            get {
                return ResourceManager.GetString("XRequired", resourceCulture);
            }
        }
    }
}
