//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuvTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuvTools.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of these parameters should be filled: {0}..
        /// </summary>
        public static string AtLeastOneTheseParametersShoudBeFilledX {
            get {
                return ResourceManager.GetString("AtLeastOneTheseParametersShoudBeFilledX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel deletion.
        /// </summary>
        public static string CancelDeletion {
            get {
                return ResourceManager.GetString("CancelDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel inclusion.
        /// </summary>
        public static string CancelInclusion {
            get {
                return ResourceManager.GetString("CancelInclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the deletion?.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm inclusion.
        /// </summary>
        public static string ConfirmInclusion {
            get {
                return ResourceManager.GetString("ConfirmInclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm registration.
        /// </summary>
        public static string ConfirmRegistration {
            get {
                return ResourceManager.GetString("ConfirmRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date {0} must be after date {1}..
        /// </summary>
        public static string DateXMustBeAfterDateY {
            get {
                return ResourceManager.GetString("DateXMustBeAfterDateY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really logout?.
        /// </summary>
        public static string DoYouReallyLogout {
            get {
                return ResourceManager.GetString("DoYouReallyLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string EmailConfirmationContentWithLinkX {
            get {
                return ResourceManager.GetString("EmailConfirmationContentWithLinkX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail confirmed..
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail {0} is already taken..
        /// </summary>
        public static string EmailXAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailXAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your search.
        /// </summary>
        public static string EnterYourSearch {
            get {
                return ResourceManager.GetString("EnterYourSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go home.
        /// </summary>
        public static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value..
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Confirmation.
        /// </summary>
        public static string LogoutConfirmation {
            get {
                return ResourceManager.GetString("LogoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed..
        /// </summary>
        public static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation performed successfully..
        /// </summary>
        public static string OperationPerformedSuccessfully {
            get {
                return ResourceManager.GetString("OperationPerformedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string PasswordResetEmailContentWithLinkX {
            get {
                return ResourceManager.GetString("PasswordResetEmailContentWithLinkX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Mail was sent..
        /// </summary>
        public static string PasswordResetMailWasSent {
            get {
                return ResourceManager.GetString("PasswordResetMailWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Successful!.
        /// </summary>
        public static string PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("PasswordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already exists..
        /// </summary>
        public static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles registered.
        /// </summary>
        public static string RolesRegistered {
            get {
                return ResourceManager.GetString("RolesRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be performed..
        /// </summary>
        public static string TheOperationCouldNotBePerformed {
            get {
                return ResourceManager.GetString("TheOperationCouldNotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you were looking for doesn&apos;t exist..
        /// </summary>
        public static string ThePageYouWereLookingForDoesntExist {
            get {
                return ResourceManager.GetString("ThePageYouWereLookingForDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no {0} registered so far..
        /// </summary>
        public static string ThereIsNoXRegisteredSoFar {
            get {
                return ResourceManager.GetString("ThereIsNoXRegisteredSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string ToConfirmDeletion {
            get {
                return ResourceManager.GetString("ToConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Not Found!.
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users registered.
        /// </summary>
        public static string UsersRegistered {
            get {
                return ResourceManager.GetString("UsersRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value outside range.
        /// </summary>
        public static string ValueOutsideRange {
            get {
                return ResourceManager.GetString("ValueOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}..
        /// </summary>
        public static string WelcomeX {
            get {
                return ResourceManager.GetString("WelcomeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        public static string XInvalid {
            get {
                return ResourceManager.GetString("XInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should be up to {1} character(s)..
        /// </summary>
        public static string XMustBeUpToYCharacters {
            get {
                return ResourceManager.GetString("XMustBeUpToYCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least {1} capital letter(s)..
        /// </summary>
        public static string XMustContainAtLeastYCapitalLetters {
            get {
                return ResourceManager.GetString("XMustContainAtLeastYCapitalLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least {1} digit(s)..
        /// </summary>
        public static string XMustContainAtLeastYDigits {
            get {
                return ResourceManager.GetString("XMustContainAtLeastYDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least {1} lower case letter(s)..
        /// </summary>
        public static string XMustContainAtLeastYLowerCaseLetters {
            get {
                return ResourceManager.GetString("XMustContainAtLeastYLowerCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string XRequired {
            get {
                return ResourceManager.GetString("XRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be equal {1}..
        /// </summary>
        public static string XShouldBeEqualY {
            get {
                return ResourceManager.GetString("XShouldBeEqualY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should have at least {1} character(s)..
        /// </summary>
        public static string XShouldHaveAtLeastYCharacters {
            get {
                return ResourceManager.GetString("XShouldHaveAtLeastYCharacters", resourceCulture);
            }
        }
    }
}
