//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuvTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuvTools.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access request not found..
        /// </summary>
        public static string AccessRequestNotFound {
            get {
                return ResourceManager.GetString("AccessRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new {0} by clicking {1}..
        /// </summary>
        public static string AddXClickingY {
            get {
                return ResourceManager.GetString("AddXClickingY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in the list..
        /// </summary>
        public static string AlreadyInList {
            get {
                return ResourceManager.GetString("AlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of these parameters should be filled: {0}..
        /// </summary>
        public static string AtLeastOneTheseParametersShoudBeFilledX {
            get {
                return ResourceManager.GetString("AtLeastOneTheseParametersShoudBeFilledX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel deletion.
        /// </summary>
        public static string CancelDeletion {
            get {
                return ResourceManager.GetString("CancelDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel inclusion.
        /// </summary>
        public static string CancelInclusion {
            get {
                return ResourceManager.GetString("CancelInclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the main address..
        /// </summary>
        public static string CannotDeleteMainAddress {
            get {
                return ResourceManager.GetString("CannotDeleteMainAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code expired..
        /// </summary>
        public static string CodeExpired {
            get {
                return ResourceManager.GetString("CodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm activation?.
        /// </summary>
        public static string ConfirmActivation {
            get {
                return ResourceManager.GetString("ConfirmActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm cancellation?.
        /// </summary>
        public static string ConfirmCancellation {
            get {
                return ResourceManager.GetString("ConfirmCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deactivation?.
        /// </summary>
        public static string ConfirmDeactivation {
            get {
                return ResourceManager.GetString("ConfirmDeactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the deletion?.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm inclusion.
        /// </summary>
        public static string ConfirmInclusion {
            get {
                return ResourceManager.GetString("ConfirmInclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm registration.
        /// </summary>
        public static string ConfirmRegistration {
            get {
                return ResourceManager.GetString("ConfirmRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete {0}. There are {1} associated..
        /// </summary>
        public static string CouldNotDeleteXExistYAssociated {
            get {
                return ResourceManager.GetString("CouldNotDeleteXExistYAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete {0}. Verify if there is associated data..
        /// </summary>
        public static string CouldNotDeleteXVerifyAssociatedData {
            get {
                return ResourceManager.GetString("CouldNotDeleteXVerifyAssociatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date {0} must be after date {1}..
        /// </summary>
        public static string DateXMustBeAfterDateY {
            get {
                return ResourceManager.GetString("DateXMustBeAfterDateY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really logout?.
        /// </summary>
        public static string DoYouReallyLogout {
            get {
                return ResourceManager.GetString("DoYouReallyLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail already registered..
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string EmailConfirmationContentWithLinkX {
            get {
                return ResourceManager.GetString("EmailConfirmationContentWithLinkX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation is different from email..
        /// </summary>
        public static string EmailConfirmationDifferentFromEmail {
            get {
                return ResourceManager.GetString("EmailConfirmationDifferentFromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail confirmed..
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail must be confirmed..
        /// </summary>
        public static string EmailMustBeConfirmed {
            get {
                return ResourceManager.GetString("EmailMustBeConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail {0} is already taken..
        /// </summary>
        public static string EmailXAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailXAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be greater than start date..
        /// </summary>
        public static string EndDateMustBeGreaterThanStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeGreaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your search.
        /// </summary>
        public static string EnterYourSearch {
            get {
                return ResourceManager.GetString("EnterYourSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error associating profile to user..
        /// </summary>
        public static string ErrorAssociatingProfileToUser {
            get {
                return ResourceManager.GetString("ErrorAssociatingProfileToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in provided parameters..
        /// </summary>
        public static string ErrorInProvidedParameters {
            get {
                return ResourceManager.GetString("ErrorInProvidedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create {0}..
        /// </summary>
        public static string FailedToCreateX {
            get {
                return ResourceManager.GetString("FailedToCreateX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete {0}..
        /// </summary>
        public static string FailedToDeleteX {
            get {
                return ResourceManager.GetString("FailedToDeleteX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate {0}..
        /// </summary>
        public static string FailedToGenerateX {
            get {
                return ResourceManager.GetString("FailedToGenerateX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update {0}..
        /// </summary>
        public static string FailedToUpdateX {
            get {
                return ResourceManager.GetString("FailedToUpdateX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go home.
        /// </summary>
        public static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpContext is not available..
        /// </summary>
        public static string HttpContextNotAvailable {
            get {
                return ResourceManager.GetString("HttpContextNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID in the object does not match the ID in the URL..
        /// </summary>
        public static string IdObjectNotMatchUrl {
            get {
                return ResourceManager.GetString("IdObjectNotMatchUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive user..
        /// </summary>
        public static string InactiveUser {
            get {
                return ResourceManager.GetString("InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect filling..
        /// </summary>
        public static string IncorrectFilling {
            get {
                return ResourceManager.GetString("IncorrectFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal service communication error..
        /// </summary>
        public static string InternalServiceCommunicationError {
            get {
                return ResourceManager.GetString("InternalServiceCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired token..
        /// </summary>
        public static string InvalidExpiredToken {
            get {
                return ResourceManager.GetString("InvalidExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type. Accepted format: {0}..
        /// </summary>
        public static string InvalidFileTypeAcceptedFormatX {
            get {
                return ResourceManager.GetString("InvalidFileTypeAcceptedFormatX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search..
        /// </summary>
        public static string InvalidSearch {
            get {
                return ResourceManager.GetString("InvalidSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value..
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code..
        /// </summary>
        public static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful..
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Confirmation.
        /// </summary>
        public static string LogoutConfirmation {
            get {
                return ResourceManager.GetString("LogoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail configuration not found..
        /// </summary>
        public static string MailConfigurationNotFound {
            get {
                return ResourceManager.GetString("MailConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not found..
        /// </summary>
        public static string NameNotFound {
            get {
                return ResourceManager.GetString("NameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found..
        /// </summary>
        public static string NoEmailTemplateFound {
            get {
                return ResourceManager.GetString("NoEmailTemplateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None parameter informed..
        /// </summary>
        public static string NoneParameterInformed {
            get {
                return ResourceManager.GetString("NoneParameterInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission to delete {0}..
        /// </summary>
        public static string NoPermissionToDeleteX {
            get {
                return ResourceManager.GetString("NoPermissionToDeleteX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed..
        /// </summary>
        public static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation performed successfully..
        /// </summary>
        public static string OperationPerformedSuccessfully {
            get {
                return ResourceManager.GetString("OperationPerformedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is different from password..
        /// </summary>
        public static string PasswordConfirmationDifferentFromPassword {
            get {
                return ResourceManager.GetString("PasswordConfirmationDifferentFromPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string PasswordResetEmailContentWithLinkX {
            get {
                return ResourceManager.GetString("PasswordResetEmailContentWithLinkX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset failed..
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Mail was sent..
        /// </summary>
        public static string PasswordResetMailWasSent {
            get {
                return ResourceManager.GetString("PasswordResetMailWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Successful!.
        /// </summary>
        public static string PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("PasswordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical file not found..
        /// </summary>
        public static string PhysicalFileNotFound {
            get {
                return ResourceManager.GetString("PhysicalFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing completed..
        /// </summary>
        public static string ProcessingCompleted {
            get {
                return ResourceManager.GetString("ProcessingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not found..
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide at least one parameter..
        /// </summary>
        public static string ProvideAtLeastOneParameter {
            get {
                return ResourceManager.GetString("ProvideAtLeastOneParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide at least one {0}..
        /// </summary>
        public static string ProvideAtLeastOneX {
            get {
                return ResourceManager.GetString("ProvideAtLeastOneX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprocessing completed..
        /// </summary>
        public static string ReprocessingCompleted {
            get {
                return ResourceManager.GetString("ReprocessingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already exists..
        /// </summary>
        public static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No roles found matching the criteria..
        /// </summary>
        public static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles registered.
        /// </summary>
        public static string RolesRegistered {
            get {
                return ResourceManager.GetString("RolesRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search returned no results. Refine your filters..
        /// </summary>
        public static string SearchNoResultsRefineFilters {
            get {
                return ResourceManager.GetString("SearchNoResultsRefineFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a profile..
        /// </summary>
        public static string SelectAProfile {
            get {
                return ResourceManager.GetString("SelectAProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template with this name already exists..
        /// </summary>
        public static string TemplateAlreadyRegistered {
            get {
                return ResourceManager.GetString("TemplateAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template not found..
        /// </summary>
        public static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text copied..
        /// </summary>
        public static string TextCopied {
            get {
                return ResourceManager.GetString("TextCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be performed..
        /// </summary>
        public static string TheOperationCouldNotBePerformed {
            get {
                return ResourceManager.GetString("TheOperationCouldNotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you were looking for doesn&apos;t exist..
        /// </summary>
        public static string ThePageYouWereLookingForDoesntExist {
            get {
                return ResourceManager.GetString("ThePageYouWereLookingForDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no {0} registered so far..
        /// </summary>
        public static string ThereIsNoXRegisteredSoFar {
            get {
                return ResourceManager.GetString("ThereIsNoXRegisteredSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string ToConfirmDeletion {
            get {
                return ResourceManager.GetString("ToConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not found..
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file is empty..
        /// </summary>
        public static string UploadedFileIsEmpty {
            get {
                return ResourceManager.GetString("UploadedFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has system access..
        /// </summary>
        public static string UserAlreadyHasSystemAccess {
            get {
                return ResourceManager.GetString("UserAlreadyHasSystemAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully..
        /// </summary>
        public static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email has not been confirmed..
        /// </summary>
        public static string UserEmailHasNotBeenConfirmed {
            get {
                return ResourceManager.GetString("UserEmailHasNotBeenConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must be active..
        /// </summary>
        public static string UserMustBeActive {
            get {
                return ResourceManager.GetString("UserMustBeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users registered.
        /// </summary>
        public static string UsersRegistered {
            get {
                return ResourceManager.GetString("UsersRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation problems were found..
        /// </summary>
        public static string ValidationProblemsFound {
            get {
                return ResourceManager.GetString("ValidationProblemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid verification code..
        /// </summary>
        public static string ValidVerificationCode {
            get {
                return ResourceManager.GetString("ValidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value outside range.
        /// </summary>
        public static string ValueOutsideRange {
            get {
                return ResourceManager.GetString("ValueOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}.
        /// </summary>
        public static string ViewX {
            get {
                return ResourceManager.GetString("ViewX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}..
        /// </summary>
        public static string WelcomeX {
            get {
                return ResourceManager.GetString("WelcomeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string XAlreadyExists {
            get {
                return ResourceManager.GetString("XAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted successfully..
        /// </summary>
        public static string XDeletedSuccessfully {
            get {
                return ResourceManager.GetString("XDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} incomplete..
        /// </summary>
        public static string XIncomplete {
            get {
                return ResourceManager.GetString("XIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        public static string XInvalid {
            get {
                return ResourceManager.GetString("XInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be equal {1}..
        /// </summary>
        public static string XMustBeEqualY {
            get {
                return ResourceManager.GetString("XMustBeEqualY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string XMustBeGreaterThanY {
            get {
                return ResourceManager.GetString("XMustBeGreaterThanY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string XMustBeLessThanY {
            get {
                return ResourceManager.GetString("XMustBeLessThanY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least {1} capital letter(s)..
        /// </summary>
        public static string XMustContainAtLeastYCapitalLetters {
            get {
                return ResourceManager.GetString("XMustContainAtLeastYCapitalLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least {1} digit(s)..
        /// </summary>
        public static string XMustContainAtLeastYDigits {
            get {
                return ResourceManager.GetString("XMustContainAtLeastYDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least {1} lower case letter(s)..
        /// </summary>
        public static string XMustContainAtLeastYLowerCaseLetters {
            get {
                return ResourceManager.GetString("XMustContainAtLeastYLowerCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain between {1} and {2} character(s)..
        /// </summary>
        public static string XMustContainBetweenYandZCharacters {
            get {
                return ResourceManager.GetString("XMustContainBetweenYandZCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must have at least {1} character(s)..
        /// </summary>
        public static string XMustHaveAtLeastYCharacters {
            get {
                return ResourceManager.GetString("XMustHaveAtLeastYCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must have up to {1} character(s)..
        /// </summary>
        public static string XMustHaveUpToYCharacters {
            get {
                return ResourceManager.GetString("XMustHaveUpToYCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        public static string XNotFound {
            get {
                return ResourceManager.GetString("XNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not provided..
        /// </summary>
        public static string XNotProvided {
            get {
                return ResourceManager.GetString("XNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} registered successfully..
        /// </summary>
        public static string XRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("XRegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string XRequired {
            get {
                return ResourceManager.GetString("XRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated successfully..
        /// </summary>
        public static string XUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("XUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} successfully..
        /// </summary>
        public static string XYSuccess {
            get {
                return ResourceManager.GetString("XYSuccess", resourceCulture);
            }
        }
    }
}
